package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final

/**
 * Email generated by hbm2java
 */
public class Email implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private Users users;
	private String title;
	private String content;
	private Accessory accessory;
	private String recipient;
	private String addresser;
	private String sendtime;
	private String receivetime;
	private Double position;
	private Double markread;

	public Email() {
	}

	public Email(String id) {
		this.id = id;
	}

	public Email(String id, Users users, Accessory accessory, String title, String content, String recipient,
			String addresser, String sendtime, String receivetime, Double position, Double markread) {
		this.id = id;
		this.users = users;
		this.accessory = accessory;
		this.title = title;
		this.content = content;
		this.recipient = recipient;
		this.addresser = addresser;
		this.sendtime = sendtime;
		this.receivetime = receivetime;
		this.position = position;
		this.markread = markread;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Accessory getAccessory() {
		return this.accessory;
	}

	public void setAccessory(Accessory accessory) {
		this.accessory = accessory;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getRecipient() {
		return this.recipient;
	}

	public void setRecipient(String recipient) {
		this.recipient = recipient;
	}

	public String getAddresser() {
		return this.addresser;
	}

	public void setAddresser(String addresser) {
		this.addresser = addresser;
	}

	public String getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}

	public String getReceivetime() {
		return this.receivetime;
	}

	public void setReceivetime(String receivetime) {
		this.receivetime = receivetime;
	}

	public Double getPosition() {
		return this.position;
	}

	public void setPosition(Double position) {
		this.position = position;
	}

	public Double getMarkread() {
		return this.markread;
	}

	public void setMarkread(Double markread) {
		this.markread = markread;
	}

}
