package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final




/**
 * Chance generated by hbm2java
 */
public class Chance implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id; //编号
	private String cname; //客户名称
	private String summary;//概要
	private String contacts;//联系人
	private String des;		//机会描述
	private String founder;	// 创建人
	private String assign;	// 指派给
	private String source;	//	机会来源
	private Double odds;	//成功几率
	private String tel;		//联系人电话
	private String ctime;	//创建时间
	private String atime;	//指派时间
	private String ch_status;//状态
	public Chance(String id, String cname, String summary, String contacts, String des, String founder, String assign,
			String source, Double odds, String tel, String ctime, String atime, String ch_status) {
		super();
		this.id = id;
		this.cname = cname;
		this.summary = summary;
		this.contacts = contacts;
		this.des = des;
		this.founder = founder;
		this.assign = assign;
		this.source = source;
		this.odds = odds;
		this.tel = tel;
		this.ctime = ctime;
		this.atime = atime;
		this.ch_status = ch_status;
	}
	public Chance() {
		super();
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getCname() {
		return cname;
	}
	public void setCname(String cname) {
		this.cname = cname;
	}
	public String getSummary() {
		return summary;
	}
	public void setSummary(String summary) {
		this.summary = summary;
	}
	public String getContacts() {
		return contacts;
	}
	public void setContacts(String contacts) {
		this.contacts = contacts;
	}
	public String getDes() {
		return des;
	}
	public void setDes(String des) {
		this.des = des;
	}
	public String getFounder() {
		return founder;
	}
	public void setFounder(String founder) {
		this.founder = founder;
	}
	public String getAssign() {
		return assign;
	}
	public void setAssign(String assign) {
		this.assign = assign;
	}
	public String getSource() {
		return source;
	}
	public void setSource(String source) {
		this.source = source;
	}
	public Double getOdds() {
		return odds;
	}
	public void setOdds(Double odds) {
		this.odds = odds;
	}
	public String getTel() {
		return tel;
	}
	public void setTel(String tel) {
		this.tel = tel;
	}
	public String getCtime() {
		return ctime;
	}
	public void setCtime(String ctime) {
		this.ctime = ctime;
	}
	public String getAtime() {
		return atime;
	}
	public void setAtime(String atime) {
		this.atime = atime;
	}
	public String getCh_status() {
		return ch_status;
	}
	public void setCh_status(String ch_status) {
		this.ch_status = ch_status;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	

	

	

	

}
