package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final



/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;  //编号
	private String name; 	//名称
	private String manager; //客户经理
	private String area; 	//地区
	private String degree;	// 客户等级
	private String satisfcing; //客户满意度
	private String addr; // 地址
	private String tel;		//电话
	private String url;//网址
	private String permitnumber;	//营业执照注册号
	private Double money;//注册资金 
	private String bank;//开户银行
	private String landtax;//地税登记号
	private String credit;//客户信用度
	private String postcode;//邮政编码
	private String fax;	//传真
	private String legalperson;//法人
	private Double annualsalse;//年营业额
	private String banknumber;//银行账号
	private String natioanaltax;//国税登记号
	private String cus_status;//状态 正常、未处理、暂缓流失、已流失  
	
	public Customer() {
		super();
	}

	public Customer(String id, String name, String manager, String area, String degree, String satisfcing, String addr,
			String tel, String url, String permitnumber, Double money, String bank, String landtax, String credit,
			String postcode, String fax, String legalperson, Double annualsalse, String banknumber, String natioanaltax,
			String cus_status) {
		super();
		this.id = id;
		this.name = name;
		this.manager = manager;
		this.area = area;
		this.degree = degree;
		this.satisfcing = satisfcing;
		this.addr = addr;
		this.tel = tel;
		this.url = url;
		this.permitnumber = permitnumber;
		this.money = money;
		this.bank = bank;
		this.landtax = landtax;
		this.credit = credit;
		this.postcode = postcode;
		this.fax = fax;
		this.legalperson = legalperson;
		this.annualsalse = annualsalse;
		this.banknumber = banknumber;
		this.natioanaltax = natioanaltax;
		this.cus_status = cus_status;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getManager() {
		return manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getDegree() {
		return degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getSatisfcing() {
		return satisfcing;
	}

	public void setSatisfcing(String satisfcing) {
		this.satisfcing = satisfcing;
	}

	public String getAddr() {
		return addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getPermitnumber() {
		return permitnumber;
	}

	public void setPermitnumber(String permitnumber) {
		this.permitnumber = permitnumber;
	}

	public Double getMoney() {
		return money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

	public String getBank() {
		return bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getLandtax() {
		return landtax;
	}

	public void setLandtax(String landtax) {
		this.landtax = landtax;
	}

	public String getCredit() {
		return credit;
	}

	public void setCredit(String credit) {
		this.credit = credit;
	}

	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getLegalperson() {
		return legalperson;
	}

	public void setLegalperson(String legalperson) {
		this.legalperson = legalperson;
	}

	public Double getAnnualsalse() {
		return annualsalse;
	}

	public void setAnnualsalse(Double annualsalse) {
		this.annualsalse = annualsalse;
	}

	public String getBanknumber() {
		return banknumber;
	}

	public void setBanknumber(String banknumber) {
		this.banknumber = banknumber;
	}

	public String getNatioanaltax() {
		return natioanaltax;
	}

	public void setNatioanaltax(String natioanaltax) {
		this.natioanaltax = natioanaltax;
	}

	public String getCus_status() {
		return cus_status;
	}

	public void setCus_status(String cus_status) {
		this.cus_status = cus_status;
	}
	
	

}
