package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final

/**
 * Linkman generated by hbm2java
 */
public class Linkman implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;	//编号
	private Customer customer;//客户编号
	private String name;//姓名
	private String sex;//性别
	private String position;//职位
	private String tel;//办公电话
	private String phone;//手机
	private String remark;//备注

	public Linkman() {
	}

	public Linkman(String id) {
		this.id = id;
	}

	public Linkman(String id, Customer customer, String name, String sex, String position, String tel, String phone,
			String remark) {
		this.id = id;
		this.customer = customer;
		this.name = name;
		this.sex = sex;
		this.position = position;
		this.tel = tel;
		this.phone = phone;
		this.remark = remark;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
