package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String usernam;
	private String name;
	private String logintime;

	public Log() {
	}

	public Log(String id) {
		this.id = id;
	}

	public Log(String id, String usernam, String name, String logintime) {
		this.id = id;
		this.usernam = usernam;
		this.name = name;
		this.logintime = logintime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsernam() {
		return this.usernam;
	}

	public void setUsernam(String usernam) {
		this.usernam = usernam;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLogintime() {
		return this.logintime;
	}

	public void setLogintime(String logintime) {
		this.logintime = logintime;
	}

}
