package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final

/**
 * Operatelog generated by hbm2java
 */
public class Operatelog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String username;
	private String name;
	private String time;
	private String level1;
	private String level2;
	private String action;

	public Operatelog() {
	}

	public Operatelog(String id) {
		this.id = id;
	}

	public Operatelog(String id, String username, String name, String time, String level1, String level2,
			String action) {
		this.id = id;
		this.username = username;
		this.name = name;
		this.time = time;
		this.level1 = level1;
		this.level2 = level2;
		this.action = action;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getLevel1() {
		return this.level1;
	}

	public void setLevel1(String level1) {
		this.level1 = level1;
	}

	public String getLevel2() {
		return this.level2;
	}

	public void setLevel2(String level2) {
		this.level2 = level2;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

}
