package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final

/**
 * RoleConRight generated by hbm2java
 */
public class RoleConRight implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;//编号
	private Rights rights;//角色id
	private Roles roles;//权限id

	public RoleConRight() {
	}

	public RoleConRight(String id) {
		this.id = id;
	}

	public RoleConRight(String id, Rights rights, Roles roles) {
		this.id = id;
		this.rights = rights;
		this.roles = roles;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Rights getRights() {
		return this.rights;
	}

	public void setRights(Rights rights) {
		this.rights = rights;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
