package com.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id; //编号
	private String rolename;//角色名称
	private String registtime;//注册时间
	private String roledes;//角色描述
	private Double role_status;//状态 停用 启用 0 \1
	private List<Rights> rights=new ArrayList<Rights>(0); 
	public Roles() {
		super();
	}
	public Roles(String id, String rolename, String registtime, String roledes, Double role_status) {
		super();
		this.id = id;
		this.rolename = rolename;
		this.registtime = registtime;
		this.roledes = roledes;
		this.role_status = role_status;
	}
	
	public Roles(String id, String rolename, String registtime, String roledes, Double role_status,
			List<Rights> rights) {
		super();
		this.id = id;
		this.rolename = rolename;
		this.registtime = registtime;
		this.roledes = roledes;
		this.role_status = role_status;
		this.rights = rights;
	}
	public List<Rights> getRights() {
		return rights;
	}
	public void setRights(List<Rights> rights) {
		this.rights = rights;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getRolename() {
		return rolename;
	}
	public void setRolename(String rolename) {
		this.rolename = rolename;
	}
	public String getRegisttime() {
		return registtime;
	}
	public void setRegisttime(String registtime) {
		this.registtime = registtime;
	}
	public String getRoledes() {
		return roledes;
	}
	public void setRoledes(String roledes) {
		this.roledes = roledes;
	}
	public Double getRole_status() {
		return role_status;
	}
	public void setRole_status(Double role_status) {
		this.role_status = role_status;
	}
	

	
}
