package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final


/**
 * Rights generated by hbm2java
 */
public class Rights implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String upright;
	private String right;
	private String name;
	private String content;
	

	public Rights() {
	}

	public Rights(String id) {
		this.id = id;
	}

	

	public Rights(String id, String upright, String right, String name, String content) {
		super();
		this.id = id;
		this.upright = upright;
		this.right = right;
		this.name = name;
		this.content = content;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUpright() {
		return upright;
	}

	public void setUpright(String upright) {
		this.upright = upright;
	}

	public String getRight() {
		return right;
	}

	public void setRight(String right) {
		this.right = right;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	
}
