package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final




/**
 * Accessory generated by hbm2java
 */
public class Accessory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3433702749740024331L;
	private String id;//
	private String path;//路径
	

	public Accessory() {
	}

	public Accessory(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Accessory(String id, String path) {
		super();
		this.id = id;
		this.path = path;
	}

	

	
	

}
