package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final



/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String logintime;//上次登录时间
	private String username;//用户名
	private String name;//姓名
	private String password;//密码
	private Roles roles;//角色
	private Usertetails detail;//用户详情
	private String user_status;//停用 启用 0/1
	public Users(String id, String logintime, String username, String name, String password, Roles roles,
			String user_status) {
		super();
		this.id = id;
		this.logintime = logintime;
		this.username = username;
		this.name = name;
		this.password = password;
		this.roles = roles;
		this.user_status = user_status;
	}
	
	public Users(String id, String logintime, String username, String name, String password, Roles roles,
			Usertetails detail, String user_status) {
		super();
		this.id = id;
		this.logintime = logintime;
		this.username = username;
		this.name = name;
		this.password = password;
		this.roles = roles;
		this.detail = detail;
		this.user_status = user_status;
	}

	public Usertetails getDetail() {
		return detail;
	}

	public void setDetail(Usertetails detail) {
		this.detail = detail;
	}

	public Users() {
		super();
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getLogintime() {
		return logintime;
	}
	public void setLogintime(String logintime) {
		this.logintime = logintime;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public Roles getRoles() {
		return roles;
	}
	public void setRoles(Roles roles) {
		this.roles = roles;
	}
	public String getUser_status() {
		return user_status;
	}
	public void setUser_status(String user_status) {
		this.user_status = user_status;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	


}
