package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final


/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;//编号
	private Customer customer;//客户ID
	private String addr; //送货地址
	private String order_status;//状态 已回款、未回款、部分回款 1、2、3
	private String cdate; //生成日期
	private String tel;//联系电话
	private Double money;//总金额
	private Double setmoney;//已结算金额
	public Orders(String id, Customer customer, String addr, String order_status, String cdate, String tel,
			Double money, Double setmoney) {
		super();
		this.id = id;
		this.customer = customer;
		this.addr = addr;
		this.order_status = order_status;
		this.cdate = cdate;
		this.tel = tel;
		this.money = money;
		this.setmoney = setmoney;
	}
	public Orders() {
		super();
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public Customer getCustomer() {
		return customer;
	}
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	public String getAddr() {
		return addr;
	}
	public void setAddr(String addr) {
		this.addr = addr;
	}
	public String getOrder_status() {
		return order_status;
	}
	public void setOrder_status(String order_status) {
		this.order_status = order_status;
	}
	public String getCdate() {
		return cdate;
	}
	public void setCdate(String cdate) {
		this.cdate = cdate;
	}
	public String getTel() {
		return tel;
	}
	public void setTel(String tel) {
		this.tel = tel;
	}
	public Double getMoney() {
		return money;
	}
	public void setMoney(Double money) {
		this.money = money;
	}
	public Double getSetmoney() {
		return setmoney;
	}
	public void setSetmoney(Double setmoney) {
		this.setmoney = setmoney;
	}
	

	
	

}
