package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;//编号
	private String cname;//客户名
	private String summary;//概要
	private String request;//服务请求
	private String creator;//创建人
	private String assign;//分配给
	private String type;//类型
	private String se_status;//状态
	private String ctime;// 创建时间
	private String atime;//分配时间
	private String discontent;//处理内容
	private String distime;//处理时间
	private String dispostor;//处理人
	private String result;//处理结果
	private Double satisficing;//满意度
	public Service(String id, String cname, String summary, String request, String creator, String assign, String type,
			String se_status, String ctime, String atime, String discontent, String distime, String dispostor,
			String result, Double satisficing) {
		super();
		this.id = id;
		this.cname = cname;
		this.summary = summary;
		this.request = request;
		this.creator = creator;
		this.assign = assign;
		this.type = type;
		this.se_status = se_status;
		this.ctime = ctime;
		this.atime = atime;
		this.discontent = discontent;
		this.distime = distime;
		this.dispostor = dispostor;
		this.result = result;
		this.satisficing = satisficing;
	}
	public Service() {
		super();
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getCname() {
		return cname;
	}
	public void setCname(String cname) {
		this.cname = cname;
	}
	public String getSummary() {
		return summary;
	}
	public void setSummary(String summary) {
		this.summary = summary;
	}
	public String getRequest() {
		return request;
	}
	public void setRequest(String request) {
		this.request = request;
	}
	public String getCreator() {
		return creator;
	}
	public void setCreator(String creator) {
		this.creator = creator;
	}
	public String getAssign() {
		return assign;
	}
	public void setAssign(String assign) {
		this.assign = assign;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getSe_status() {
		return se_status;
	}
	public void setSe_status(String se_status) {
		this.se_status = se_status;
	}
	public String getCtime() {
		return ctime;
	}
	public void setCtime(String ctime) {
		this.ctime = ctime;
	}
	public String getAtime() {
		return atime;
	}
	public void setAtime(String atime) {
		this.atime = atime;
	}
	public String getDiscontent() {
		return discontent;
	}
	public void setDiscontent(String discontent) {
		this.discontent = discontent;
	}
	public String getDistime() {
		return distime;
	}
	public void setDistime(String distime) {
		this.distime = distime;
	}
	public String getDispostor() {
		return dispostor;
	}
	public void setDispostor(String dispostor) {
		this.dispostor = dispostor;
	}
	public String getResult() {
		return result;
	}
	public void setResult(String result) {
		this.result = result;
	}
	public Double getSatisficing() {
		return satisficing;
	}
	public void setSatisficing(Double satisficing) {
		this.satisficing = satisficing;
	}

	
}
