package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final

/**
 * Usertetails generated by hbm2java
 */
public class Usertetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;//
//	private Users users;//用户
	private Datadic job;//职位
	private Datadic depart;//部门
	private String regdate;//注册日期
	private String tel;//电话
	private String sex;//性别 男  女
	public Usertetails(String id, Datadic job, Datadic depart, String regdate, String tel, String sex) {
		super();
		this.id = id;
		
		this.job = job;
		this.depart = depart;
		this.regdate = regdate;
		this.tel = tel;
		this.sex = sex;
	}
	public Usertetails() {
		super();
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
//	public Users getUsers() {
//		return users;
//	}
//	public void setUsers(Users users) {
//		this.users = users;
//	}
	public Datadic getJob() {
		return job;
	}
	public void setJob(Datadic job) {
		this.job = job;
	}
	public Datadic getDepart() {
		return depart;
	}
	public void setDepart(Datadic depart) {
		this.depart = depart;
	}
	public String getRegdate() {
		return regdate;
	}
	public void setRegdate(String regdate) {
		this.regdate = regdate;
	}
	public String getTel() {
		return tel;
	}
	public void setTel(String tel) {
		this.tel = tel;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	
	
	
}
