package com.model;
// Generated 2018-7-27 19:52:01 by Hibernate Tools 3.5.0.Final

/**
 * Sharedoc generated by hbm2java
 */
public class Sharedoc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;//编号
	private Datadic datadic;//类别
	private String title;//标题：
	private String time;//上传日期
	private String name;//上传人：
	public Sharedoc() {
		super();
	}
	public Sharedoc(String id, Datadic datadic, String title, String time, String name) {
		super();
		this.id = id;
		this.datadic = datadic;
		this.title = title;
		this.time = time;
		this.name = name;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public Datadic getDatadic() {
		return datadic;
	}
	public void setDatadic(Datadic datadic) {
		this.datadic = datadic;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getTime() {
		return time;
	}
	public void setTime(String time) {
		this.time = time;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	

}
